video_chatt_app/urls.py
from django.urls import path
from video_chatt_app import views 

app_name = 'video_chatt_app'
urlpatterns = [
	path('',views.index,name = 'index'),
	path('create_meeting/',views.create_meeting,name="create_meeting"),
	path('join_meeting/',views.join_meeting,name = "join_meeting"),
	path('schedule_meeting/',views.schedule_meeting,name = "schedule_meeting"),
	path('check_for_meetingid/',views.check_for_meetingid,name = 'check_for_meetingid'),
	path('student_join_meeting/',views.student_join_meeting,name = 'student_join_meeting'),
	path('upload_question/',views.upload_question,name = "upload_question"),
	path('get_question/',views.get_question,name = "get_question"),
	path('question_response/',views.question_response,name="question_response"),
	path('student_info/',views.student_info,name="student_info"),
	path('intrac_tutor/',views.intract_tutor,name="intrac_tutor"),
	path('insert_question/',views.insert_question,name= "insert_question"),
	path('get_dashboard_data/',views.get_dashboard_data,name="get_dashboard_data"),
	path('teacher_dashboard/',views.teacher_dashboard,name="teacher_dashboard"),
	path('add_topic/',views.add_topic,name ="add_topic"),
	path('upload_topic/',views.upload_topic,name ="upload_topic"),

]

video_chatt_pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('video_chatt_app.urls')),
    path('login/', views.login,{'template_name':'video_chatt_app/Login.html'}, name='login'),
    path('logout/',views.logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
]

video_chatt_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Role(models.Model):
	name = models.CharField(max_length = 100)

	def __str__(self):
		return self.name

class UserGrade(models.Model):
	student_grade = models.IntegerField()


class AttentionSpain(models.Model):
	user_grade = models.ForeignKey(UserGrade,on_delete=models.CASCADE)
	attention_span = models.BigIntegerField()



class UserRole(models.Model):
	user_id= models.ForeignKey(User, on_delete=models.CASCADE)
	role_id = models.ForeignKey(Role, on_delete=models.CASCADE)

class TeacherGrade(models.Model):
	user_id = models.ForeignKey(User, on_delete=models.CASCADE)
	grade_id  = models.ForeignKey(UserGrade, on_delete=models.CASCADE)

class StudentGrade(models.Model):
	user_id = models.ForeignKey(User,on_delete = models.CASCADE)
	grade_id  = models.ForeignKey(UserGrade, on_delete=models.CASCADE)



class Subject(models.Model):
	subject_name = models.CharField(max_length = 100)

	def __str__(self):
		return self.subject_name


class Topic(models.Model):
	topic_name = models.CharField(max_length = 100)
	subject_id = models.ForeignKey(Subject,on_delete=models.CASCADE)

	def __str__(self):
		return self.topic_name

class Questions(models.Model):
	topic_id = models.ForeignKey(Topic,on_delete = models.CASCADE)
	question = models.TextField()

	def __str__(self):
		return self.question

class Answer(models.Model):
	question_id = models.ForeignKey(Questions,on_delete = models.CASCADE)
	option1 = models.CharField(max_length = 100)
	option2 = models.CharField(max_length = 100)
	correct_answer = models.CharField(max_length = 100,null = True)


class subject_teacher(models.Model):
	subject_id = models.ForeignKey(Subject,on_delete= models.CASCADE)
	user_id = models.ForeignKey(User,on_delete = models.CASCADE)

class user_parent(models.Model):
	parent_name = models.CharField(max_length = 100)
	user_id = models.ForeignKey(User,on_delete = models.CASCADE)



class UserMeeting(models.Model):
	user_id = models.ForeignKey(User, on_delete=models.CASCADE)
	meeting_id = models.BigIntegerField()
	grade_id = models.ForeignKey(UserGrade,on_delete = models.CASCADE)
	meeting_subject = models.ForeignKey(Subject,on_delete = models.CASCADE)
	meeting_topic = models.ForeignKey(Topic,on_delete = models.CASCADE)
	meet_start = models.DateTimeField(auto_now_add=True)
	meet_end = models.DateTimeField(null=True,blank=True)

class User_attendence(models.Model):
	user_id= models.ForeignKey(User, on_delete=models.CASCADE)
	meeting_id = models.ForeignKey(UserMeeting,on_delete=models.CASCADE)

class StudentReport(models.Model):
	user_id = models.ForeignKey(User,on_delete = models.CASCADE)
	meeting_id = models.ForeignKey(UserMeeting,on_delete = models.CASCADE)
	question_id = models.ForeignKey(Questions,on_delete = models.CASCADE)
	question_time = models.DateTimeField(auto_now_add = True)
	answer_time = models.DateTimeField(null=True)
	answer_corrent = models.CharField(max_length = 100,null = True)

video_chatt_app/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from . models import *
from django.http import JsonResponse
import random
import datetime
from django.db.models import Q

# Create your views here.


@login_required
def index(request):
	user_obj = User.objects.get(username = request.user.username)
	user_role = UserRole.objects.filter(user_id = user_obj)[0]
	user_grade = TeacherGrade.objects.filter(user_id = user_obj)
	subject_list = subject_teacher.objects.filter(user_id = user_obj)
	user_role_info = user_role.role_id.name
	student_role_id = Role.objects.get(name = 'student')
	student_list = UserRole.objects.filter(role_id = student_role_id)
	topic_list = []
	total_student_count = total_session_attended(request.user.username)
	student_attentiveness = total_student_attentivness(request.user.username)
	accurate_response = total_accurate_response(request.user.username)
	for subject in subject_list:
		topic_obj = Topic.objects.filter(subject_id = subject.subject_id)
		topic_list.append(topic_obj)
	data = {
		'user_role_info':user_role_info,
		'user_grade':user_grade,
		'subject_list':subject_list,
		'topic_list':topic_list,
		'student_list':student_list,
		'total_student_count':total_student_count,
		'student_attentiveness':student_attentiveness,
		'accurate_response':accurate_response

	}
	if user_role_info == 'teacher':
		return render(request,'video_chatt_app/home.html',context=data)
	else:
		return redirect('/join_meeting/')


def total_session_attended(username):
	user_obj = User.objects.get(username = username)
	user_metting_obj = UserMeeting.objects.filter(user_id = user_obj)
	count = 0
	for user_meeting in user_metting_obj:
		user_attendence_obj = User_attendence.objects.filter(meeting_id = user_meeting)
		count = count+len(user_attendence_obj)
	return count


def total_student_attentivness(username):
	user_obj = User.objects.get(username = username)
	teacher_meeting_obj = UserMeeting.objects.filter(user_id = user_obj)
	total_question = 0 
	user_response = 0 
	student_attentiveness = 0
	for meeting_obj in teacher_meeting_obj:
		student_report_obj = StudentReport.objects.filter(meeting_id = meeting_obj)
		total_question = total_question+len(student_report_obj)
		for student_data in student_report_obj:
			if student_data.answer_time:
				user_response = user_response+1
	if user_response and total_question:
		student_attentiveness = "{:.2f}".format((user_response/total_question)*100)
	return student_attentiveness


def total_accurate_response(username):
	user_obj = User.objects.get(username = username)
	teacher_meeting_obj = UserMeeting.objects.filter(user_id = user_obj)
	total_question = 0 
	user_correct_response = 0 
	accurate_response = 0
	for meeting_obj in teacher_meeting_obj:
		student_report_obj = StudentReport.objects.filter(meeting_id = meeting_obj)
		total_question = total_question+len(student_report_obj)
		for student_data in student_report_obj:
			if student_data.answer_corrent == 'yes':
				user_correct_response = user_correct_response+1
	if user_correct_response and total_question:
		accurate_response = "{:.2f}".format((user_correct_response/total_question)*100)
	return accurate_response



@login_required
def create_meeting(request):
	user_obj = User.objects.get(username = request.user.username)
	subject_list = subject_teacher.objects.filter(user_id = user_obj)
	user_grade = TeacherGrade.objects.filter(user_id = user_obj)
	user_role = UserRole.objects.filter(user_id = user_obj)[0]
	user_role_info = user_role.role_id.name
	topic_list = []
	for subject in subject_list:
		topic_obj = Topic.objects.filter(subject_id = subject.subject_id)
		topic_list.append(topic_obj)
	data = {
		'subject_list':subject_list,
		'topic_list':topic_list,
		'user_grade':user_grade,
		'user_role_info':user_role_info
	}
	return render(request,'video_chatt_app/create_meeting.html',context=data)


@login_required
def schedule_meeting(request):
	requested_sub = request.GET.get('subject', None)
	requested_topic = request.GET.get('topic', None)
	requested_grade = request.GET.get('grade', None)
	user_meeting_obj = 1
	while user_meeting_obj:
		meeting_id = random.randint(4444,77778886655)
		try:
			user_meeting_obj = UserMeeting.objects.get(meeting_id = meeting_id)
		except:
			user_meeting_obj = 0
	try:
		user_meeting = UserMeeting(
							user_id =  User.objects.get(username = request.user.username),
							meeting_id = meeting_id,
							grade_id = UserGrade.objects.get(student_grade = int(requested_grade)),
							meeting_subject = Subject.objects.get(subject_name = requested_sub),
							meeting_topic = Topic.objects.get(topic_name = requested_topic)
							)
		user_meeting.save()
		data = {
			'meeting_id':meeting_id
		}
		return JsonResponse(data)
	except Exception as err:
		print('error fetching details:', err)


@login_required
def join_meeting(request):
	user_obj = User.objects.get(username = request.user.username)
	user_role = UserRole.objects.filter(user_id = user_obj)[0]
	user_role_info = user_role.role_id.name
	return render(request,'video_chatt_app/join_meeting.html',{'user_role_info':user_role_info})




@login_required
def check_for_meetingid(request):
	meeting_id = request.GET.get('meetingId', None)
	try:
		user_meeting = UserMeeting.objects.get(meeting_id = meeting_id)
		data = {
			'metting_value' :True
		}
	except:
		data = {
			'metting_value' :False
		}
	return JsonResponse(data)

@login_required
def student_join_meeting(request):
	meeting_id = request.GET.get('meetingId', None)
	meeting_name = request.GET.get('meetingName', None)
	try:
		student_grade_obj = StudentGrade.objects.get(user_id = User.objects.get(username = request.user.username))
		attention_span_obj = AttentionSpain.objects.get(user_grade = student_grade_obj.grade_id)
		user_attandance_obj = User_attendence(
								user_id = User.objects.get(username = request.user.username),
								meeting_id = UserMeeting.objects.get(meeting_id = meeting_id)
							)
		user_attandance_obj.save()
		data = {
			'mesaage':'Marked Attandance',
			'attention_span':attention_span_obj.attention_span
		}
		return JsonResponse(data)
	except Exception as err:
		print('error fetching details: ', err)


@login_required
def upload_question(request):
	user_obj = User.objects.get(username = request.user.username)
	subject_list = subject_teacher.objects.filter(user_id = user_obj)
	grade_list = TeacherGrade.objects.filter(user_id = user_obj)
	user_role = UserRole.objects.filter(user_id = user_obj)[0]
	user_role_info = user_role.role_id.name
	topic_list = []
	for subject in subject_list:
		topic_obj = Topic.objects.filter(subject_id = subject.subject_id)
		topic_list.append(topic_obj)
	data = {
		'subject_list':subject_list,
		'topic_list':topic_list,
		'user_role_info':user_role_info,
		'grade_list':grade_list
	}
	return render(request,'video_chatt_app/upload_question.html',context=data)


@login_required
def get_question(request):
	meeting_id = request.GET.get('meetingId', None)
	user_obj = User.objects.get(username = request.user.username)
	user_meeting_obj = UserMeeting.objects.get(meeting_id= meeting_id)
	user_question = Questions.objects.filter(topic_id = user_meeting_obj.meeting_topic)
	questions_list = []
	for item in user_question:
		questions_list.append(item)
	try:
		random_question = random.choice(questions_list)
		question_instance = Questions.objects.get(id = random_question.id)
		answer_obj = Answer.objects.get(question_id = question_instance)
		student_report_obj = StudentReport(
								user_id = user_obj,
								meeting_id = user_meeting_obj,
								question_id = question_instance,
							)
		student_report_obj.save()
		data = {
			'student_report_id':student_report_obj.id,
			'id':random_question.id,
			'topic_id':random_question.topic_id.topic_name,
			'question':random_question.question,
			'option1':answer_obj.option1,
			'option2':answer_obj.option2
		}
		return JsonResponse(data)
	except Exception as err:
		print('error fetching details:', err)

@login_required
def question_response(request):
	try:
		student_report_id = request.GET.get('studentReportId', None)
		response_answer = request.GET.get('responseAnswer', None)
		student_response_obj = StudentReport.objects.get(id = student_report_id)
		answer_obj = Answer.objects.get(question_id = student_response_obj.question_id)
		if answer_obj.correct_answer == response_answer:
			student_response_obj.answer_corrent = 'yes'
			student_response_obj.answer_time = datetime.datetime.now()
			student_response_obj.save()
			data = {
				'message':'Correct Answer'
			}
		else:
			student_response_obj.answer_corrent = 'no'
			student_response_obj.answer_time = datetime.datetime.now()
			student_response_obj.save()
			data = {
				'message':'Wrong Answer'
			}
		return JsonResponse(data)
	except Exception as err:
		print('error fetching details: ', err)

@login_required
def student_info(request):
	try:
		user_obj = User.objects.get(username = request.user.username)
		user_role = UserRole.objects.filter(user_id = user_obj)[0]
		user_role_info = user_role.role_id.name
		student_grade = StudentGrade.objects.filter(user_id = user_obj)[0]
		# accurate_response = get_student_attentivness(user_obj)
		data = {
			# 'student_grade':student_grade,
			'user_role_info':user_role_info
		}
		return render(request, 'video_chatt_app/student_info.html',context=data)
	except Exception as err:
		print('Error fetching details:', err)


# def get_student_attentivness(user_obj):
# 	total_question = 0 
# 	user_response = 0 
# 	student_attentiveness = 0
# 	studengt_response = StudentReport.objects.filter(user_id = user_obj)
# 	total_question = total_question+len(studengt_response)
# 	for response in studengt_response:
# 		if response.answer_time:
# 			user_response = user_response+1
# 	if user_response and total_question:
# 		student_attentiveness = "{:.2f}".format((user_response/total_question)*100)
# 	return student_attentiveness

templates/video_chatt_app/Login.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Teacher Assist</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link rel="stylesheet" type="text/css" href="{%static 'css/login.css'%}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="wrapper fadeInDown">
        <div id="formContent">
          <!-- Tabs Titles -->
          <div class="fadeIn first">
            <span class="title"><img style="height:5.5rem; width:11rem" src="./../../static/images/TeacherAssist_Final-removebg.png" alt="Picture"></span>
          </div>
          <!-- Login Form -->
          <form method="post">
            {% csrf_token %}
            <input type="text" class="fadeIn second" name="username" id="id_username" placeholder="Username" required>
            <input type="password" name="password"  id="id_password" class="fadeIn third" name="login" placeholder="Password" required>
            <input type="submit" class="fadeIn fourth" value="Log In">
          </form>
      
        </div>
      </div>
</body>
</html>

templates/video_chatt_app/add_topic.html
{%extends 'video_chatt_app/base.html'%}
{%block content%}
  <style>
    .background {
      background-color: #f6f6f6;
    }

    .shadow {
      -webkit-box-shadow: 0 10px 30px 0 rgba(95, 186, 233, 0.4);
      box-shadow: 0 10px 30px 0 rgba(95, 186, 233, 0.4);
      -webkit-border-radius: 5px 5px 5px 5px;
      border-radius: 5px 5px 5px 5px;
      margin: 5px 20px 40px 20px;
      -webkit-transition: all 0.3s ease-in-out;
      -moz-transition: all 0.3s ease-in-out;
      -ms-transition: all 0.3s ease-in-out;
      -o-transition: all 0.3s ease-in-out;
      transition: all 0.3s ease-in-out;
    }
  </style>
        <div class="well form-horizontal border shadow p-5 background" 
          id="question_form" style="margin-top: 1rem;">
          <fieldset>

            <!-- Form Name -->
            <legend>
              <center>
                <div>
                  <h1 style="color:#56baed">Add Topic</h1>
                </div>
              </center>
            </legend><br>
            <div class="alert alert-danger" role="alert" id="upload-alert" style="display:none;">
            </div>
            <!-- Text input-->
            <!-- <center> -->
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label class="col-md-12 control-label">Subject :</label>
                  <div class="col-md-12 selectContainer">
                    <div class="input-group">
                      <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
                      <select name="subject" class="form-control selectpicker" id="select-subject">
                        <option value="" selected disabled>Select your Subject</option>
                        {%for subject in subject_list%}
                        <option>{{subject.subject_name}}</option>
                        {%endfor%}
                      </select>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                    <label class="col-md-12 control-label">Topic :</label>
                    <div class="col-md-12 inputGroupContainer">
                      <div class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                        <input id = "input-topic" name="question" placeholder="Topic" class="form-control" type="text">
                      </div>
                    </div>
                  </div>
              </div>
            </div>
            <center>
              <div class="form-group">
                <div class="col-md-12">
                  <br>
                  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<button
                    id="submit-button" class="btn btn-primary"
                    style="background-color: #56baed;">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspSUBMIT <span
                      class="glyphicon glyphicon-send"></span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</button>
                </div>
              </div>
            </center>
          </fieldset>
        </div>

<script>
$('#submit-button').click(function(){
  var selected_sub = $('#select-subject').val();
  var selected_topic = $('#input-question').val();
  if (selected_sub && selected_topic ){
     $.ajax({
        url: '/upload_topic/',
        data: {
            'selectedSub':selected_sub,
            'selectedTopic':selected_topic,
        },
        dataType: 'json',
        success: function (data) {
            $('#upload-alert').html(data.message);
            $('#upload-alert').removeClass("alert-danger");
            $('#upload-alert').addClass("alert-success");
            $('#upload-alert').css('text-align','center');
            $('#upload-alert').css('display','block');
            var selected_sub = $('#select-subject').val('');
            var selected_topic = $('#topicDropdown').val('');
        }
    });

  }
  else{
    $('#upload-alert').removeClass("alert-success");
    $('#upload-alert').addClass("alert-danger");
    $('#upload-alert').html('Please select and fill all the fields');
    $('#upload-alert').css('display','block');
    $('#upload-alert').css('text-align','center');
  }

})
</script>
{%endblock%}

templates/video_chatt_app/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Teacher Assist</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

  <!-- Custom styles for this template -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <link href="{%static 'css/home.css'%}" rel="stylesheet">
  <link href="{%static 'css/join_meeting.css'%}" rel="stylesheet">
  <link href="{%static 'css/interact_tutor.css'%}" rel="stylesheet">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>

<body>

  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading"><a href="{%url 'video_chatt_app:index'%}">Teacher Assist</a></div>
      <div class="list-group list-group-flush">
        <a href="{%url 'video_chatt_app:join_meeting'%}" class="list-group-item list-group-item-action bg-light">Join Meeting</a>
        {% if user_role_info == 'student' %}
        <a href="{%url 'video_chatt_app:student_info'%}" class="list-group-item list-group-item-action bg-light">Student information</a>
        <a href="{%url 'video_chatt_app:intrac_tutor'%}" class="list-group-item list-group-item-action bg-light">Interact With Tutor</a>
        {%endif%}
        {% if user_role_info == 'teacher' %}
        <a href="{%url 'video_chatt_app:create_meeting'%}" class="list-group-item list-group-item-action bg-light">Host Meeting</a>
        <a href="{%url 'video_chatt_app:upload_question'%}" class="list-group-item list-group-item-action bg-light">Upload Questions</a>
        <a href="{%url 'video_chatt_app:add_topic'%}" class="list-group-item list-group-item-action bg-light">Add Topic</a>
      <!--   <a href="#" class="list-group-item list-group-item-action bg-light">Export Report</a> -->
        {% endif %}
      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <button class="btn btn-primary" id="menu-toggle"><span class="navbar-toggler-icon"></span></button>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!-- <span class="title">Teacher Assist</span> -->
        <span class="title"><img style="height: 43px;width: 62px;" src="./../../static/images/TeacherAssist_Final-removebg.png" alt="Picture"></span>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                 <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M3 14.828v9.172h18v-9.172l-9-8.375-9 8.375zm11 7.172h-4v-6h4v6zm10-9.852l-1.361 1.465-10.639-9.883-10.639 9.868-1.361-1.465 12-11.133 12 11.148z"/></svg>
                {{user.get_username}}
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Account</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{%url 'logout'%}">Log Out</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>

      <div class="container-fluid">
        {%block content%}
        {%endblock%}
      </div>
        
    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->


  <!-- Menu Toggle Script -->
  <script src='https://meet.jit.si/external_api.js'></script>
  <script type="text/javascript" src="{%static 'js/custom.js'%}"></script>
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

</body>

</html>

templates/video_chatt_app/student_info.html
{%extends 'video_chatt_app/base.html'%}
{%block content%}
<style>
    .booking-card-student{
-webkit-box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
  box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
}
</style>
<div class="container" id ="vedio-chatt-room">

    <div class="well form-horizontal border shadow p-5 background" id="formContent"
      style="margin-top: 1rem; height:550px">
      <legend>
        <center>
          <div>
            <h1 style="color:#56baed">Student Information</h1>
          </div>
        </center>
      </legend><br>
      <div class="row">
        <div class="col-md-4">
            <!-- Card -->
            <div class="booking-card-student topMargin">

                <!-- Card image -->
                <div class="view overlay">
                    <img class="card-img-top"
                        src="./../../static/images/student_avatar.jpg"
                        alt="Card image cap">
                </div>

            </div>
            <!-- Card -->
        </div>
    <div class="col-md-8">
        <h4 class="card-title font-weight-bold" style="color:#56baed"><a>Details</a></h4>
                    <!-- Data -->
                    <p class="mb-2"><strong>Name:</strong> John Doe</p>
                    <p class="mb-2"><strong>Roll No:</strong> 23</p>
                    <p class="mb-2"><strong>Grade:</strong> 9</p>
                    <p class="mb-2"><strong>Overall Attentiveness:</strong> 80%</p>
                    <p class="mb-2"><strong>Accurate Response:</strong> 70%</p>
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id=tutormode>
                        <label class="form-check-label" for="exampleCheck1">Recommend Tutor</label>
                    </div>
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id=low_attendance>
                        <label class="form-check-label" for="exampleCheck1">Trigger E-mail to parent (Low Attendance)</label>
                    </div>


    </div>
</div>
    </div>
  </div>
 
{%endblock%}